// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD33qXjCD7ILRKbNxrBJWBBCVtok8ElBKk',
    appId: '1:298176635969:web:1979ca5122085d732252c0',
    messagingSenderId: '298176635969',
    projectId: 'social-posts-acb56',
    authDomain: 'social-posts-acb56.firebaseapp.com',
    storageBucket: 'social-posts-acb56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6PsIR8xhlvqGRrSH6fnc-IlxHQtxiZY',
    appId: '1:298176635969:android:ee8e05666b6d7abd2252c0',
    messagingSenderId: '298176635969',
    projectId: 'social-posts-acb56',
    storageBucket: 'social-posts-acb56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBOTEn51cFGf06cG_-QUH5a-skR-T8FY',
    appId: '1:298176635969:ios:84bff9f43e343d9f2252c0',
    messagingSenderId: '298176635969',
    projectId: 'social-posts-acb56',
    storageBucket: 'social-posts-acb56.appspot.com',
    iosClientId: '298176635969-bhrnkculjnu238costrup1bcim01okd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialUiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwBOTEn51cFGf06cG_-QUH5a-skR-T8FY',
    appId: '1:298176635969:ios:84bff9f43e343d9f2252c0',
    messagingSenderId: '298176635969',
    projectId: 'social-posts-acb56',
    storageBucket: 'social-posts-acb56.appspot.com',
    iosClientId: '298176635969-bhrnkculjnu238costrup1bcim01okd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialUiKit',
  );
}
